### ISSUE TITLE
enum / enumNames

### ISSUE THREAD

**Issue by kozy** [wittydeveloper/functional-json-schema#4]
Hi, me again :)

I really like this clean way of building a schema.  I'm trying to build this structure but I cannot figure out how to do it. Is it possible and would you be so kind to guide me? I would like to use it to augment the react-apollo-form.  

```
data: {
  properties: {
    date_of_birth: {
      type: "string",
      "format": "date"
    },
    gender: {
      "enum": [
        'MALE',
        'FEMALE'
      ],
      "enumNames": [
        "Male",
        "Female"
      ]
    }
  }
}
```
Thank you!

**Comment by wittydeveloper** [comment]
Hi @kozy ,

I found this issue on `json-schema` repo that explains how to handle `enumNames`: https://github.com/mozilla-services/react-jsonschema-form/issues/532
